"""
Django settings for docmanager_backend project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Load environment from backend/.env (dev convenience)
try:
    from dotenv import load_dotenv
except Exception:  # pragma: no cover
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv:
    load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d!d5*@we-8x49@sq9gur$&p-o1xg^oy0j^hvvi9kish3^_d_#s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Lock down in production via env var / nginx


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'corsheaders',

    # Local
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'docmanager_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'docmanager_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

def _env(name: str, default: str | None = None) -> str | None:
    return os.environ.get(name, default)

# Default to MSSQL; override with DJANGO_DB_ENGINE=sqlite only if needed
DB_ENGINE = _env('DJANGO_DB_ENGINE', 'mssql')
if DB_ENGINE == 'mssql':
    trust_cert = _env('DJANGO_DB_TRUST_CERT', 'true') == 'true'
    encrypt = _env('DJANGO_DB_ENCRYPT', 'true') == 'true'

    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': _env('DJANGO_DB_NAME', 'FileManager'),
            'USER': _env('DJANGO_DB_USER', ''),
            'PASSWORD': _env('DJANGO_DB_PASSWORD', ''),
            'HOST': _env('DJANGO_DB_HOST', 'TOEHSQL1'),
            'PORT': _env('DJANGO_DB_PORT', '1433'),
            'OPTIONS': {
                # Example: ODBC Driver 18 for SQL Server
                'driver': _env('DJANGO_DB_ODBC_DRIVER', 'ODBC Driver 18 for SQL Server'),

                # Use extra_params so the options land in the ODBC connection string exactly.
                # This avoids "Invalid connection string attribute" errors.
                'extra_params': (
                    f"Encrypt={'yes' if encrypt else 'no'};"
                    f"TrustServerCertificate={'yes' if trust_cert else 'no'};"
                ),
            },
        }
    }
elif DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ValueError(f"Unsupported DJANGO_DB_ENGINE: {DB_ENGINE!r}. Use 'mssql' or 'sqlite'.")

# CORS (lock down later)
CORS_ALLOW_ALL_ORIGINS = _env('DJANGO_CORS_ALLOW_ALL', 'true') == 'true'
CORS_ALLOW_CREDENTIALS = True  # required for cross-origin session cookies

# Session / CSRF cookie settings
# Behind nginx (same domain), use Lax. Only use None for true cross-origin dev.
# Set DJANGO_SESSION_COOKIE_SECURE=true when behind HTTPS (production).
_cookie_secure = _env('DJANGO_SESSION_COOKIE_SECURE', 'false').lower() == 'true'
_cookie_samesite = _env('DJANGO_SESSION_COOKIE_SAMESITE', 'Lax')

SESSION_COOKIE_SAMESITE = _cookie_samesite
SESSION_COOKIE_SECURE = _cookie_secure
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = _cookie_samesite
CSRF_COOKIE_SECURE = _cookie_secure

# REST Framework defaults
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Serve media via nginx at /file/media/
MEDIA_URL = '/file/media/'
MEDIA_ROOT = _env('DJANGO_MEDIA_ROOT', str(BASE_DIR / 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
